### PR TITLE
Removing Internal Details from ETL Status API Response

### PR DESCRIPTION
**Pull request by ccaprio97**
## What’s changing?

taking out ID and Publisher from ETL status api respose

## Why?

NAC-1063

## This PR has:

- [X] **Commented source code** (_required on public classes and methods, and elsewhere as appropriate_)

- [ ] **Developer documentation** (_for new build/test/API changes or complex portions of the system_)

- [ ] **Automated unit tests** (_to maintain or increase level of code coverage_)

- [ ] **Changes to IAC** (_add any deployment steps that require manual intervention to the draft release notes_)

### CODE REVIEW

**Comment by ccaprio97** [comment]
did some googling and this seemed like the only way something about it still worries me though because its on the class itself and not done after making the object

**Comment by dborgen2** [comment]
Yea, I've been talking with Conner offline. JsonIgnore is the right thing to use to not pass variables when serialized by Newtonsoft, I wanted to make sure this wouldn't affect the database though, but it looks like it doesn't. We should be good here. Removing from the constructor should be unnecessary, so he's going to try adding it back in and making sure it still works. Assuming so, I can approve.

**Review by dborgen2 — APPROVED** [review]
👍

**Review by bgfoshay — CHANGES_REQUESTED** [review]
Question: Can you add a test that serializes the object and verifies that the outputted json does not contain those properties?

**Review by bgfoshay — APPROVED** [review]
Thanks for adding the test! 

Nitpick: There might be a little bit of extra overhead in the test but it covers the change you made.

**Pull request merged**
