### PR TITLE
Enable soft blob delete with a retention period of 1 day

### PR DESCRIPTION
**Pull request by edwintorres**
## What’s changing?

Soft blob delete was enabled on Azure Storage.

## Why?

Issue #2312 

## This PR has:

- [ ] **Commented source code** (_required on public classes and methods, and elsewhere as appropriate_)

- [ ] **Developer documentation** (_for new build/test/API changes or complex portions of the system_)

- [ ] **Automated unit tests** (_to maintain or increase level of code coverage_)

- [X] **Changes to IAC** (_add any deployment steps that require manual intervention to the draft release notes_)

### CODE REVIEW

**Comment by kingcomma** [comment]
@edwintorres  Sorry, it took me longer to get to this than it should have.

*Question:* Does this new `shareDeleteRetentionPolicy` property apply to the storage account's blob service? I don't see the property in the [Microsoft.Storage/storageAccounts](https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts?tabs=json) or [Microsoft.Storage/storageAccounts/blobServices](https://docs.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts/blobservices?tabs=json) resources.

**Comment by edwintorres** [comment]
@kingcomma I researched this, I think I used an old API https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.storage.models.fileserviceproperties.sharedeleteretentionpolicy?view=azure-dotnet

I'm looking at how to do it with the new API. Thank for this catch.

**Review by kingcomma — APPROVED** [review]
👍 Looks good to me! Apologies for taking so long to get back to this.

**Comment by kingcomma** [comment]
Jira/NAC-142

**Pull request merged**
