### PR TITLE
Added lds_hash as required field

### LINKED ISSUE #1722: Update CSV schema to make `lds_hash` a required field
Currently the `lds_hash` field is constrained only by a regex pattern. Consequently, a row that contains no value for `lds_hash` will pass validation. This is in conflict with the BulkUpload function app which will throw exceptions for rows with no value for `lds_hash`.

Update `import-schema.json` with a `"required": true` constraint.

### PR DESCRIPTION
**Pull request by edwintorres**
## What’s changing?

Update import-schema.json with a "required": true constraint.

## Why?

Close #1722 

## This PR has:

- [ ] **Commented source code** (_required on public classes and methods, and elsewhere as appropriate_)

- [X] **Developer documentation** (_for new build/test/API changes or complex portions of the system_)

- [ ] **Automated unit tests** (_to maintain or increase level of code coverage_)

- [ ] **Changes to IAC** (_add any deployment steps that require manual intervention to the draft release notes_)

### CODE REVIEW

**Comment by kingcomma** [comment]
*Question:* Did you intend to [delete](https://github.com/18F/piipan/pull/2523/files#diff-9e7d871d792efe330a59b4c31e6c78d717806e2bfd8a5f989abaab92d5b09455) `dashboard/src/Piipan.Dashboard/package-lock.json` in this PR?

**Comment by edwintorres** [comment]
@kingcomma no intentionally, I didn't notice that.

**Comment by edwintorres** [comment]
@kingcomma fixed it

**Review by kingcomma — APPROVED** [review]
👍

**Pull request merged**
