### PR TITLE
Various visual updates to Query Tool

### LINKED ISSUE #1379: Additional query tool text/style updates
I have completed my [prioritized recommendations for UX/UI changes for the query tool](https://docs.google.com/document/d/1Wy0H6XiKu61QjNEB3yNzqOT4lWIWfJzJr6jPoe2kQLk/edit#heading=h.wxneopr4sf8p).

Below are the items I would suggest implementing at present: 

### Overall page

- [x] Update the banner (GH Issue #1014)
- [x] Add definition to query form area: 
  - [x] Add border between banner and form
  - [x] Add border between form and results
Screen Shot 2021-08-13 at 5 17 42 PM
- [x] Increase space after Search button: Try margin-bottom at 3.5rem?

### Form UX/UI

- [x] Improve formatting of error messages
  - [x] Remove width constraint on error message: In the current implementation, the error message is constrained to the width of the form. Let’s remove width constraint so that the error message text doesn’t wrap on desktop.  
- [x] Edits to the SSN error message:
  - [x] Let’s match the error message to the helper formatting: `000-00-0000` → `xxx-xx-xxxx`
  - [x] Add a period to the end of the error message to match other error messages: `SSN must have the form xxx-xx-xxxx.`
- [x] Consider using the [slim alert formatting](https://designsystem.digital.gov/components/alert/) from the USWDS 
image
- [x] Improve error messages for Date of birth field
  - [x] If I don’t input anything into the form and hit Search I see this:
Screen Shot 2021-08-13 at 5 20 03 PM
I assume the “The value “ is invalid.” responds to the date field being empty. 
Change this to: `The Date of birth field is required.`
  - [x] Currently I’m not able to trigger error messages for DOBs with a year that is implausible. 
  Display error message for DOBs with a year before 1900 and after the current year: `The Date of birth must have a year between 1900 – [current year].`

### Results UX/UI
- [x] Capitalize the state abbreviations: `ea` → `EA` to conform with standard formatting of two letter state abbreviations
- [x] Change column header for `Protected location for vulnerable individuals`: Change this column header to be more concise:
  - header should be `Protect location?`
- [x] Change the color of the header column to match color palette: Use the primary blue with white text. 
Screen Shot 2021-08-13 at 5 23 13 PM

### PR DESCRIPTION
**Pull request by echappen**
Closes #1379 and #1014

### Notes
- Making Date of Birth property nullable allowed more descriptive error
messages. Otherwise, the generic server-side 'Value "" is invalid' error shows up on empty date submissions. More info:
https://stackoverflow.com/questions/43281345/mvc-net-core-model-validation-the-value-is-invalid-error
- Custom attribute validation was needed in order to accept a variable current date as part of the date range. More info:
https://dotnettutorials.net/lesson/custom-validation-attribute-mvc/
- I'm starting a directory pattern/convention for SASS files—open to thoughts.

### Screenshots

Screen Shot 2021-08-17 at 11 41 40 AM

----

Screen Shot 2021-08-17 at 11 42 02 AM

----

Screen Shot 2021-08-17 at 11 41 40 AM

----

Screen Shot 2021-08-17 at 11 43 33 AM

### CODE REVIEW

**Comment by juliaklindpaintner** [comment]
@echappen This is looking really good! Can you upload a couple more screenshots:
- what the bad formatting on SSN error message looks like
- what the error message looks like for a DOB before 1900
- the whole page before conducting a search
- the whole page after conducting a search that results in a match
Thanks!

**Comment by echappen** [comment]
@juliaklindpaintner Here you go!

SSN error:
Screen Shot 2021-08-17 at 3 19 21 PM

----

DOB range error:
Screen Shot 2021-08-17 at 3 19 43 PM

----

Whole page pre-search (my screen is only 13" so I did it in parts)
Screen Shot 2021-08-17 at 3 20 11 PM
Screen Shot 2021-08-17 at 3 20 19 PM

----

Whole page post-search with result
Screen Shot 2021-08-17 at 3 20 53 PM
Screen Shot 2021-08-17 at 3 21 01 PM

**Comment by juliaklindpaintner** [comment]
@echappen Thank you! Did you know you can [use Chrome's dev tools to take a full screenshot](https://umaar.com/dev-tips/151-screenshot-capture/)? 

Just a couple little notes: 

1. Change `Date of birth must be between 01-01-1900 and Current Date.` to `Date of birth must be between 01-01-1900 and today's date.`
2. Add more space beneath the results table — should be the same amount of white space as is between the search button and the CUI banner before running a search.

One more thing (but I wouldn't hold up merging this PR on account of this). I love the formatting of the No results banner now, and am wondering if the error message banner can look a little cleaner. Currently the `!` symbol isn't in line with the text. Can we bring those into line? Ideally, if there were only one error, it wouldn't even need a bullet, but that seems more complicated. Looking for something like this: 
image

**Comment by echappen** [comment]
@juliaklindpaintner All updated. Here's a new error list:

Screen Shot 2021-08-17 at 4 42 31 PM

**Comment by echappen** [comment]
Also some full-size screens for you!

localhost_5001_ (1)

localhost_5001_ (2)

**Comment by juliaklindpaintner** [comment]
@echappen Amazing! Thanks so much. I'm going to go ahead and approve!

**Review by juliaklindpaintner — APPROVED** [review]
LGTM!

**Comment by echappen** [comment]
@juliaklindpaintner Thanks! @kingcomma Mind giving this code a looksie before I merge? Wanted to see if my SASS file structure makes sense to others before I move forward.

**Review by kingcomma — APPROVED** [review]
LGTM!

Only (non-blocking) thing I noticed is that `usda-symbol-color.png` is being added but doesn't appear to be used.

**Pull request merged**
