### PR TITLE
Add specs for recent benefits months in CSV import schema

### PR DESCRIPTION
**Pull request by echappen**
partially addresses #861 

I'd like to get consensus on these specs for the CSV import, since it'll inform how the data is parsed and stored. 

This new CSV column would look like this:
| recent benefit months |
|---|
| 2/2021,3/2021,4/2021 |
| 1/2021,3/2021,4/2021 |
| 1/2021,2/2021,3/2021 |

Does this look alright?

### CODE REVIEW

**Comment by ryanhofdotgov** [comment]
This seems like a good example of just always using ISO 6801 for formatting dates, as it already has a defined format; i.e. YYYY-MM

Using commas within a CSV field is allowed, but CSV generators/readers tend not to implement it super well. It requires the field be double-quoted. Space delimited might be better here.

**Comment by ryanhofdotgov** [comment]
Tying it back to our other conversation about me regretting not using ISO 8601 from the get-to for the DOB:
I think I might open up a PR to deprecate the MM/DD/YYYY format, update the spec/test files to be YYYY-MM-DD, and update the ETL code to (temporarily) support both DOB formats.

**Comment by echappen** [comment]
Yeah I was wondering about doing that conversion in a separate PR, instead of incorporating it into one of these other API changes. But as we continue to add dates, it's becoming apparent to just do it earlier than later.

**Comment by echappen** [comment]
@ryanhofdotgov I also wanted to confirm that this description in the import schema is correct:

> Does not include current benefit month. Months do not need to be consecutive.

**Comment by ryanhofdotgov** [comment]
@echappen Can you point me to where that text is from? I see: "These months would be consecutive"

**Comment by echappen** [comment]
Ah, totally missed that. Will change.

**Comment by kingcomma** [comment]
What is the expected value for this field for participants who have been active for less than 3 months in a state's system? I.e., if a participant is new to the state in `May 2021` and the state is submitting a bulk upload in `June 2021`, would that participant's `recent benefit months` field contain only one month (`5/2021`)?

If so, does the `format` or description need to be updated to reflect the possibility that the field would hold less than 3 dates.

**Comment by kingcomma** [comment]
On the topic of date formatting, I think there may be another argument for ISO 8601 — I'm getting the following error when validating the `benefits end month` field (I must have missed this in prior review) against a value of `5/2021`:

```
CastError('Field "benefits end month" can\'t cast value "5/2021" for type "yearmonth" with format "%m/%Y"')
```

Upon re-reading the [table schema docs](https://specs.frictionlessdata.io/table-schema/#yearmonth) it looks like `yearmonth` does not support a `format` property.

**Comment by echappen** [comment]
Good catch @kingcomma! I removed the formatting for the yearmonth column, and added some language to indicate that less than 3 months can be entered.

**Pull request closed without merging**
