### PR TITLE
Use managed identity when metrics functions connect to database

### LINKED ISSUE #409: Convert Metrics Database authentication to managed identity
In order to keep our database resources more consistent, we should convert the metrics database to use a managed identity instead of the current admin username and password.

### PR DESCRIPTION
**Pull request by kingcomma**
- Update connection strings, switching user to system-assigned identity
- Remove unnecessary Key Vault configuration
- Move system-assigned identity creation to initial function creation command
- Update application code to use managed identity and shared authentication library when building database connection string

Closes #409.

IaC has been run against `tts/dev`.

Deploy notes:
- Manually delete unused `kv-metrics` Key Vault
- Manually revoke permissions in `kv-core` for each Function app:
```
principalId=$(az functionapp identity show \
  -g "RESOURCE_GROUP" \
  -n "$METRICS_COLLECT_APP_NAME" \
  --query principalId \
  -o tsv)
az keyvault delete-policy \
  -n "$VAULT_NAME" \
  --object-id "$principalId"
```

### CODE REVIEW

**Comment by kingcomma** [comment]
Converting this to a draft — it looks like there may be an overlooked issue with the Metrics Collector.

**Comment by kingcomma** [comment]
@ryanhofdotgov @echappen Opening this back up — the issue I saw was related to #1100 and the fix (#1107) is not related to these changes. Sorry for the churn, this is now ready for review.

**Review by echappen — APPROVED** [review]
👍

**Comment by kingcomma** [comment]
Manual IaC commands have been run against `tts/dev`.

**Pull request merged**
