### PR TITLE
Initial database schema for match records

### PR DESCRIPTION
**Pull request by kingcomma**
Partially address #1546 — starting with the database schema before getting into implementation.

Trying to keep this as simple as possible for meeting the needs of the ticket, knowing that requirements are still coming into focus and the underlying implementation is likely to change.

### CODE REVIEW

**Review by echappen — COMMENTED** [review]
_question_: Would we want an `updated_at` in addition to a `created_at`? Or maybe a `closed_at`?

_question_: Would `initiator` be a state name, or a something like “bulk match”? 

_question_: How does a match record the “other” state being matched? (Based on my assumption that `initiator` would be the initiating state)

**Comment by kingcomma** [comment]
@echappen In general, I'm trying to toe the line between what's required for this specific ticket and what we know we will need in the future. Specifically:

> _question_: Would we want an `updated_at` in addition to a `created_at`? Or maybe a `closed_at`?

Agree that some form of both `updated_at` and `created_at` will be necessary in the near future, but left them out absent a current use case.

> _question_: Would `initiator` be a state name, or something like “bulk match”?

This perhaps goes against my thinking above, but I left this loosely defined intentionally thinking it would currently capture the initiating state name, and may be adapted to capture the method used to identify the match (e.g., `bulk` or `api`) if/when the states involved in a match are recorded as relationships.

> _question_: How does a match record the “other” state being matched? (Based on my assumption that `initiator` would be the initiating state)

The `data` column would contain the API response which in turn contains the other state(s) in the match. I was envisioning this initial implementation as more like the old lookup records for now (recording a match event and all associated data), refining over time as the user stories dictate things like [pair-wise matches](https://gsa-tts.slack.com/archives/C018P1ZJPEC/p1632182331045300?thread_ts=1632172097.042200&cid=C018P1ZJPEC) (for example).

**Comment by echappen** [comment]
_suggestion_: Thinking through how this data will be queried down the road... which states the matches pertain to is probably something that will be queried pretty often, like when checking if an open match already exists. Keeping the matching state data in a jsonb field makes a sql query slightly more complicated and more brittle if that json structure should change. It may make the queries more straightforward to break out that data into its own field like `matching_state` or something, that stores the state abbreviation as text or enum.

**Comment by kingcomma** [comment]
@echappen Based on our discussion, I added a `states` column that accepts an array of two text values. Like we said, this should make it easier to perform the work necessary for #1549. E.g.,:

```
SELECT *
FROM matches
WHERE hash=@hash
  AND hash_type=@hash_type
  AND states @> @states 
  AND states <@ @states
```

I went with `states` as the name of the column to match the `state` property in the API responses.

**Review by echappen — APPROVED** [review]

**Pull request merged**
