### PR TITLE
update query tool name in deployment

### PR DESCRIPTION
**Pull request by echappen**
Changed the name of query tool app in iac so had to change it in deployment too

### CODE REVIEW

**Review by ryanhofdotgov — APPROVED** [review]
👍 but query tool app name is actually a globally scoped resource. No worries – we will fix that up again when we pick up: https://github.com/18F/piipan/issues/660

There's quite a few things to add the prefix and/or environment to, including keyvault, databases, etc. Plus resource types to databases and identities.

**Comment by echappen** [comment]
This may be a good time for me to confirm how to check whether or not a resource is global. I was referencing the Location of the resource—if it's in a region (like West US) vs "Global." Is this the right way to check?

Screen Shot 2021-04-13 at 8 46 19 AM

**Comment by kingcomma** [comment]
I've been relying on the "scope" column in this doc from MS: [Naming rules and restrictions for Azure resources](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules)

The naming scope is separate from a resource's location. E.g., two APIM resources (which have a globally scoped naming requirement) in different locations can't share the same name.

**Comment by echappen** [comment]
Perfect, thanks!

**Pull request merged**
