### PR TITLE
Update CsvHelper

### PR DESCRIPTION
**Pull request by ryanhofdotgov**

### CODE REVIEW

**Comment by ryanhofdotgov** [comment]
CsvHelper update from v19 to v21 is not backwards compatible, will require some code changes:
```
BulkUpload.cs(72,13): error CS0200: Property or indexer 'IReaderConfiguration.HasHeaderRecord' cannot be assigned to -- it is read only [/root/project/etl/src/Piipan.Etl/Piipan.Etl.csproj]
BulkUpload.cs(73,13): error CS0200: Property or indexer 'IParserConfiguration.TrimOptions' cannot be assigned to -- it is read only [/root/project/etl/src/Piipan.Etl/Piipan.Etl.csproj]
BulkUpload.cs(74,31): error CS1061: 'IReaderConfiguration' does not contain a definition for 'RegisterClassMap' and no accessible extension method 'RegisterClassMap' accepting a first argument of type 'IReaderConfiguration' could be found (are you missing a using directive or an assembly reference?) [/root/project/etl/src/Piipan.Etl/Piipan.Etl.csproj]
```

**Comment by ryanhofdotgov** [comment]
There's lots of churn on CsvHelper over past week or so. And there are [releases on nuget.org](https://www.nuget.org/packages/CsvHelper/) that aren't (yet?) [tagged in GitHub](https://github.com/JoshClose/CsvHelper/releases). Going to sit on this for at least a week or so before updating our code to work with this new version.

**Comment by kingcomma** [comment]
@ryanhofdotgov I didn't flag you on [my comment on the previous PR](https://github.com/18F/piipan/pull/229#issuecomment-762888090) for the CsvHelper bump. Adding it here just because it took me a minute to find the relevant code changes in the docs' Getting Started section.

**Comment by ryanhofdotgov** [comment]
Ah, thanks @kingcomma – I ignored all the notifications on the dependabot PRs and hadn't realized there was some signal there.

**Comment by ryanhofdotgov** [comment]
I had forgotten this was a PR instead of an issue; closing in lieu of https://github.com/18F/piipan/issues/433

**Pull request closed without merging**
