### PR TITLE
query tool website style/text updates

### LINKED ISSUE #1013: NAC website text / format changes
Presumably the low-hanging fruit for the UI/UX enhancements of #890.

**update with contents of #914**

**Query form (root page):**
- [ ] Remove “NAC Query Tool” heading
- [ ] Change "Search for SNAP Participants" to an h2 element (and do the same on the query results page)
- [ ] Add " (optional)" to Middle name field label (and do the same on the query results page)
  - [ ] bonus: make “(optional)” slightly lighter, e.g.  #757575 (USWDS gray-50)
- [ ] Add "(xxx-xx-xxxx)" to SSN field label (and do the same on the query results page)
  - [ ] bonus: make “(optional)” slightly lighter, e.g.  #757575 (USWDS gray-50)
- [ ] Change "Submit" on the form to "Search" (and do the same on the query results page)
- [ ] Change order of name fields to First, Middle, Last (and do the same on the query results page). Main goal is to sync format / order with query and lookup ID results, open to taking the lowest-effort path.
- [ ] Place date of birth field above SSN to match the query results table
- [ ] Change page title from “NAC Query Tool - Piipan.QueryTool” to ”NAC Participant Search”

**Query results page:**
- [ ] Remove “NAC Query Results” heading
- [ ] Change "Benefits End" heading to "Benefits end"

**~~Lookup by ID page (/LookupById):~~**
- ~~Remove "NAC Query Tool" heading~~
- ~~Make "Search by Lookup ID" an h2 element (should also apply to the search results page)~~
- ~~Change "Submit" button to "Search" (should also apply to the search results page)~~
- ~~Add " (7 digits)" to the Lookup ID field label (should also apply to the search results page)~~
  - ~~bonus: make “(7 digits)” slightly lighter, e.g.  #757575 (USWDS gray-50)~~
- ~~Change page title from “NAC Query Tool - Piipan.QueryTool” to ”NAC Participant Lookup”~~

### PR DESCRIPTION
**Pull request by echappen**
Closes #1013 

### Screenshots

Screen Shot 2021-08-12 at 11 16 26 AM

---

Screen Shot 2021-08-12 at 11 16 17 AM

### CODE REVIEW

**Review by juliaklindpaintner — APPROVED** [review]
LGTM! One question: Any reason National Accuracy Clearinghouse can't all be on one line?

**Comment by echappen** [comment]
@juliaklindpaintner It's a default USWDS Nav thing—since there's no logo, text is there instead. Want me to see if we can pull it out of the Nav and make it the H1?

Screen Shot 2021-08-12 at 4 39 33 PM

**Comment by ryanhofdotgov** [comment]
@echappen Would conforming to the stylesheet's expectations by adding [a USDA logo](https://www.usda.gov/themes/usda/img/usda-symbol.svg) also make it look better/wrap better?

**Comment by juliaklindpaintner** [comment]
I may be able to give better direction on this as soon as I've finished reviewing the UX/UI recs, which I'm hoping to have finished today. Here is what I had been thinking of previously, following the USDA style guide for banners. But I'm not sure NAC rises to the level that would use this.
Screen Shot 2021-08-13 at 10 10 46 AM

Perhaps hold on this styling — it doesn't need to hold up this PR.

**Comment by echappen** [comment]
Ok will hold on header for now—thanks @juliaklindpaintner!

**Pull request merged**
