### PR TITLE
Add solution files for each subsystem

### PR DESCRIPTION
**Pull request by echappen**
Addresses #157 

- 1 sln per subsystem
- subsystem sln includes test projects

### CODE REVIEW

**Review by ryanhofdotgov — APPROVED** [review]
Would it be possible to add a quick cheat sheet to creating them from an existing .csproj, how it affects builds, or testing, dependency updates, etc.? 

Michael and I believed solution files would make our lives better, but admittedly now what we have these, I don't know what to do with them 😂  

In particular, I see that the docs are Visual Studio heavy vs Visual Studio Code.

**Comment by ryanhofdotgov** [comment]
Also, doesn't need to hold up this PR, but didn't see a .sln for the ETL code.

**Comment by echappen** [comment]
I... don't really know what to do with them either 🤣 but I'll keep researching!

**Comment by echappen** [comment]
After some more research and [discussion with other TTS folks](https://gsa-tts.slack.com/archives/C02CD5VUQ/p1616509321008100), it seems the main benefit has to do with having more strategic and faster builds as your projects grow. 

I still haven't found much detail on how exactly .NET achieves this, or how exactly solutions are useful outside of Visual Studio. All the official Microsoft docs are Visual Studio-specific. The closest I could find was [this](https://garywoodfine.com/creating-editing-solution-files-dotnet-core-ubuntu/):

> Although not strictly necessary from a pure development perspective, we don’t necessarily need solution files when developing with VS Code, but solution files do come in handy during the Build and Release phases of projects, so it is generally good practice to start thinking about using them in the early stages of your project development.

For now, even though we're working in VSCode, it's still sort of nice to only run `dotnet build` once at the `.sln` level, instead of having to build every project at the `.csproj` level.

**Comment by ryanhofdotgov** [comment]
@echappen Cool – let's incorporate as a part of our workflow and see how it goes.

**Pull request merged**
